### ISSUE TITLE
SOLDIER attribute code?

### ISSUE THREAD

**Issue by ppriyank** [moon-wh/MADE#2]
The Github link for the solder attribute generator is missing. Is it a mistake? 

Thanks a lot for your code.

**Comment by Vi-Sri** [comment]
I think the training code for SOLIDER is provided to train the PAR model. You need to get the PETA mat and  dataset pkl file for PETA dataset from 

https://github.com/tinyvision/SOLIDER-PersonAttributeRecognition/tree/master/data/PETA

and use the following file map 
[file_map.txt](https://github.com/moon-wh/MADE/files/14429612/file_map.txt)

to train the SOLIDER PAR model on PETA dataset and use https://github.com/moon-wh/MADE/blob/master/SOLIDER/demo_PETA_prcc.py  and similar ones to generate Attribute meta file. I was able to train the PAR model to generate attributes though.

**Comment by Acedess** [comment]
> I think the training code for SOLIDER is provided to train the PAR model. You need to get the PETA mat and dataset pkl file for PETA dataset from
> 
> https://github.com/tinyvision/SOLIDER-PersonAttributeRecognition/tree/master/data/PETA
> 
> and use the following file map [file_map.txt](https://github.com/moon-wh/MADE/files/14429612/file_map.txt)
> 
> to train the SOLIDER PAR model on PETA dataset and use https://github.com/moon-wh/MADE/blob/master/SOLIDER/demo_PETA_prcc.py and similar ones to generate Attribute meta file. I was able to train the PAR model to generate attributes though.

Could you tell me how should the "file_map.txt" be used to train the SOLIDER PAR model on PETA dataset? And how should I organize the files in /data/PETA/images? Thanks!

**Comment by Acedess** [comment]
> I think the training code for SOLIDER is provided to train the PAR model. You need to get the PETA mat and dataset pkl file for PETA dataset from
> 
> https://github.com/tinyvision/SOLIDER-PersonAttributeRecognition/tree/master/data/PETA
> 
> and use the following file map [file_map.txt](https://github.com/moon-wh/MADE/files/14429612/file_map.txt)
> 
> to train the SOLIDER PAR model on PETA dataset and use https://github.com/moon-wh/MADE/blob/master/SOLIDER/demo_PETA_prcc.py and similar ones to generate Attribute meta file. I was able to train the PAR model to generate attributes though.

I encountered KeyError: 'swin_t' when I ran demo_PETA_prcc.py. Have you encountered the same error? I’m sure I have trained the SOLIDER PAR model on PETA dataset with swin_transfomer_tiny backbone, and I have modify the model and dataset path.

**Comment by moon-wh** [comment]
> I think the training code for SOLIDER is provided to train the PAR model. You need to get the PETA mat and dataset pkl file for PETA dataset from
> 
> https://github.com/tinyvision/SOLIDER-PersonAttributeRecognition/tree/master/data/PETA
> 
> and use the following file map [file_map.txt](https://github.com/moon-wh/MADE/files/14429612/file_map.txt)
> 
> to train the SOLIDER PAR model on PETA dataset and use https://github.com/moon-wh/MADE/blob/master/SOLIDER/demo_PETA_prcc.py and similar ones to generate Attribute meta file. I was able to train the PAR model to generate attributes though.

That's right, thanks.

**Comment by moon-wh** [comment]
> I think the training code for SOLIDER is provided to train the PAR model. You need to get the PETA mat and dataset pkl file for PETA dataset from
> 
> https://github.com/tinyvision/SOLIDER-PersonAttributeRecognition/tree/master/data/PETA
> 
> and use the following file map [file_map.txt](https://github.com/moon-wh/MADE/files/14429612/file_map.txt)
> 
> to train the SOLIDER PAR model on PETA dataset and use https://github.com/moon-wh/MADE/blob/master/SOLIDER/demo_PETA_prcc.py and similar ones to generate Attribute meta file. I was able to train the PAR model to generate attributes though.

That's right, thanks.
