### ISSUE TITLE
Clarification needed on the meaning of N in attribute list and sequence length

### ISSUE THREAD

**Issue by BorgDiven** [moon-wh/MADE#6]
Hello authors,

Thank you for sharing the code and paper for your interesting "Masked Attribute Description Embedding for Cloth-Changing Person Re-identification" work. I had a question about a detail in the methodology that I was hoping you could clarify.

In Section 3.2 "Description Extraction and Mask (DEM)", you write:

"Given a sample xi, input SOLIDER to get persons' attributes list [ai1, ai2 , . . . , aiN ], and convert them into 0-1 binary vectors by position. We implement the clothing information mask operation by setting the clothing attributes to 0. And, the masked attribute description data [mi1, mi2, . . . , miN ] with the clothing information removed is obtained."

Then later in Section 3.3 "Process of Description Embedding", you mention:

"First, we segment the image xi into a sequence of N = H × W/P2 fixed-size, where P represents the size of the patch, and then map the patch sequence through a trainable linear projection as one- dimensional notation {f vj |Nj=1}."

I wanted to clarify - is the N used in the attribute list [ai1, ai2 , . . . , aiN ] referring to the total number of attributes detected for the person or the same definition of N used later to refer to the number of image patch tokens, defined as N = H × W/P2?

Thank you in advance for your help! I look forward to your response.

**Comment by moon-wh** [comment]
Thank you for your correction. In fact, these two terms are not related at all. I will revise it in my upcoming paper.

**Comment by BorgDiven** [comment]
Thank you for the quick response and confirmation that the two N terms are distinct.

In Section 3.2, you mention that given a sample xi, SOLIDER outputs a persons' attributes list [ai1, ai2 , . . . , aiN ], which is then converted to a 0-1 binary vector. My interpretation is that N represents the total number of attributes detected for the person, and the resulting binary vector has dimensions [N, 1], with each element representing the presence (1) or absence (0) of a specific attribute.

Could you please confirm if my understanding is correct?

**Comment by moon-wh** [comment]
Yes, it's right. And it's dimension is [1, N].

**Comment by BorgDiven** [comment]
Thank you!
